### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by hidayatmn378** [OceanParcels/parcels_gallery#2]
Hello! My name is Nur, I was trying to plot your code and create bathymetry, but it seems I get this error message when I execute it.

HTTPError: HTTP Error 403: Forbidden

For clarity, I attached the file: https://github.com/hidayatmn378/Ocean-Modelling/blob/main/bathymetry_plot_cartopy.ipynb

Do you have any thoughts?

**Comment by erikvansebille** [comment]
Perhaps @cpierard or @CKehl can help?

**Comment by CKehl** [comment]
Hi - I see your problem. It seems that the nacisdn website requires an SSH-HTTP access. That won't work as intended.

We are seeking and try to resolve this by providing another link for automated internet download protocol to the bathymetry data, if available. We'll get back to you.

**Comment by CKehl** [comment]
I just checked - you setup of this line is slightly incorred:

`ax.add_feature(cart.feature.NaturalEarthFeature(category='physical',name='LAND',scale='110m'),color='grey', zorder=0)`

the following works (see non-capitalization of 'name'):

`ax.add_feature(cart.feature.NaturalEarthFeature(category='physical',name='land',scale='110m'),color='grey', zorder=0)`

**Comment by hidayatmn378** [comment]
Thank you so much for your help
